### ISSUE TITLE
Unable to override CELERY_QUEUES

### ISSUE THREAD

**Issue by firaskafri** [just-work/django-celery-rpc#84]
In ```create_celery_app``` it seems to be overriding ```CELERY_QUEUES```  with:

```
    app.conf.update(
        CELERY_HIGH_PRIORITY_QUEUE=high_q,
        CELERY_HIGH_PRIORITY_ROUTING_KEY=high_rk,
        CELERY_QUEUES=(Queue(q, routing_key=rk),
                       Queue(high_q, routing_key=high_rk)))
```

Wouldn't it be better if it could be overridden in ```CELERY_RPC_CONFIG```?  If so please let me know so I can submit a pull request

**Comment by firaskafri** [comment]
Use case: requesting several services workers to execute a task which requires ```fanout```/```broadcast``` queue

**Comment by ttyS15** [comment]
Oh! Interesting! 

We didn`t  think about such feature. 🤔 How will you plan to handle task results from several workers?

**Comment by firaskafri** [comment]
@ttyS15 typically in broadcast situation celery does not [recommend having results ](https://docs.celeryproject.org/en/stable/userguide/routing.html#broadcast) ```ignore_result```.

I'm thinking this is useful for ```call``` while for model operations a ```direct``` queue is required.

Not sure if this is the best approach, what do you think?

**Comment by ttyS15** [comment]
Do you have a real need for this feature? If so, I think it can be accepted.

@SergeyTikhonov What do you think? Truly, I can`t imagine where it can be useful.

**Comment by firaskafri** [comment]
I'm assuming this package was designed for micro-services communication? Sometimes in such architectures you'd need to dispatch some events for several services without expecting any results such as a notification that some data was updated?
So instead of having another package to dispatch similar events in django, why not just have it as well?

I would appreciate it if you have another suggestion/approach

**Comment by ttyS15** [comment]
> I'm assuming this package was designed for micro-services communication?

**Comment by firaskafri** [comment]
@ttyS15 that is awesome! my bad have not explored the rest of your repos! I was merely proposing having this in one independent package but now that I see the actual work it seems it would be better separated!

**Comment by tumb1er** [comment]
I knew there was word "event" under fanout/broadcast coverage :)
BTW, celery-amqp-events is not in production yet, planning in early 2021.
